// react-channel-app-integration/src/component/min-card-only.js
import React from "react";

const MinCardOnly = ({customer}) => {
    let customerName = customer.customerName;
    let customerAddress = customer.customerAddress;
    
  return (
    <div>
    
      <form id="MinCardOnly">
        <div className="row mb-3">
          <div className="col-sm-12">
            <div className="row gy-5 cc-pad-bottom-20">
              <div className="col-12 title-border-bottom">
                <strong>DEFAULT NAME & ADDRESS</strong>
              </div>
            </div>
            <div className="row cc-pad-bottom-40">
              <div className="col-xxl-6 col-xl-6 col-lg-6 col-md-6 col-sm-12">
                <label htmlFor="jump-first-name" className="form-label">
                  <strong>First name:</strong> {customerName.firstName}
                </label>
                <div name="jump-first-name" type="text"></div>
              </div>
              <div className="col-xxl-6 col-xl-6 col-lg-6 col-md-6 col-sm-12">
                <label htmlFor="jump-last-name" className="form-label">
                <strong>Last name:</strong> {customerName.lastName}
                </label>
                <div name="jump-last-name" type="text"></div>
              </div>
            </div>

            <div className="row gy-3 cc-pad-bottom-10">
              <div className="col-xxl-6 col-xl-6 col-lg-6 col-md-6 col-sm-12">
                <label className="form-label"><strong>Address:</strong> {customerAddress.address}</label>
                <div name="jump-address" type="text"></div>
              </div>
              <div className="col-xxl-6 col-xl-6 col-lg-6 col-md-6 col-sm-12">
                <label className="form-label"><strong>Line2:</strong> {customerAddress.addressLine2}</label>
                <div name="jump-line2" type="text"></div>
              </div>
              <div className="col-xxl-4 col-xl-4 col-lg-4 col-md-4 col-sm-12">
                <label className="form-label"><strong>City:</strong> {customerAddress.city}</label>
                <div name="jump-city" type="text"></div>
              </div>
              <div className="col-xxl-4 col-xl-4 col-lg-4 col-md-4 col-sm-12">
                <label className="form-label"><strong>State:</strong> {customerAddress.state}</label>
                <div name="jump-state" type="text"></div>
              </div>
              <div className="col-xxl-4 col-xl-4 col-lg-4 col-md-4 col-sm-12">
                <label className="form-label"><strong>Zip code:</strong> {customerAddress.zipCode}</label>
                <div name="jump-zip-code" type="text"></div>
              </div>
            </div>
          </div>
        </div>
      </form>

    </div>
  );
};

export default MinCardOnly;

// angular-channel-app-integration/src/app/payments/min-card-only/min-card-only.component.ts
import { Component, OnInit  } from '@angular/core';
import { PaymentService } from '../payment.service';

@Component({
  selector: 'min-card-only',
  templateUrl: './min-card-only.component.html',
  styleUrls: ['./min-card-only.component.css']
})
export class MinCardOnlyComponent implements OnInit {
  title = 'minimum card only component';
  customerInfo:any = Object.assign({});
  
  constructor(private paymentService:PaymentService) {
  }
  ngOnInit(){
    this.customerInfo = this.paymentService.getCustomerDetail();
  }
}

<div>
  <form id="MinCardOnly">
    <div class="row mb-3">
      <div class="col-sm-12">
        <div class="row gy-5 cc-pad-bottom-20 style-pad-bottom-20">
          <div class="col-12 style-border-bottom">
            <strong>DEFAULT NAME & ADDRESS</strong>
          </div>
        </div>
        <div class="row cc-pad-bottom-40 style-pad-bottom-40">
          <div class="col-xxl-6 col-xl-6 col-lg-6 col-md-6 col-sm-12">
            <label for="jump-first-name" class="form-label">
              <strong>First name:</strong> {{customerInfo.firstName}}
            </label>
            <div name="jump-first-name" type="text"></div>
          </div>
          <div class="col-xxl-6 col-xl-6 col-lg-6 col-md-6 col-sm-12">
            <label for="jump-last-name" class="form-label">
              <strong>Last name:</strong> {{customerInfo.lastName}}
            </label>
            <div name="jump-last-name" type="text"></div>
          </div>
        </div>

        <div class="row gy-3 cc-pad-bottom-20 style-pad-bottom-20">
          <div class="col-xxl-6 col-xl-6 col-lg-6 col-md-6 col-sm-12">
            <label class="form-label"
              ><strong>Address:</strong> {{customerInfo.address}}</label
            >
            <div name="jump-address" type="text"></div>
          </div>
          <div class="col-xxl-6 col-xl-6 col-lg-6 col-md-6 col-sm-12">
            <label class="form-label"
              ><strong>Line2:</strong> {{customerInfo.addressLine2}}</label
            >
            <div name="jump-line2" type="text"></div>
          </div>
          <div class="col-xxl-4 col-xl-4 col-lg-4 col-md-4 col-sm-12">
            <label class="form-label"
              ><strong>City:</strong> {{customerInfo.city}}</label
            >
            <div name="jump-city" type="text"></div>
          </div>
          <div class="col-xxl-4 col-xl-4 col-lg-4 col-md-4 col-sm-12">
            <label class="form-label"
              ><strong>State:</strong> {{customerInfo.state}}</label
            >
            <div name="jump-state" type="text"></div>
          </div>
          <div class="col-xxl-4 col-xl-4 col-lg-4 col-md-4 col-sm-12">
            <label class="form-label"
              ><strong>Zip code:</strong> {{customerInfo.zip}}</label
            >
            <div name="jump-zip-code" type="text"></div>
          </div>
        </div>
      </div>
    </div>
  </form>
</div>
